# config_iot_ros.yaml 
# IoT Configuration
config_iot:
  mqtt:
    server_url: "broker.mqttdashboard.com"        # http://www.hivemq.com/demos/websocket-client/
    server_port: 1883
    topic_sub: "eyrc/gliffind/iot_to_ros"          # <unique_id> = xYzqLm
    topic_pub: "eyrc/gliffind/ros_to_iot"          # <unique_id> = xYzqLm
    qos: 0

    sub_cb_ros_topic: "/ros_iot_bridge/mqtt/sub"   # ROS nodes can listen to this topic to receive data from MQTT
  url: "AKfycbygqa5aGx3uhf-6LiTARBTewjo1jBjIw1DeH2FH7sdC09CJLNJh"